<template>
<div class="wrapper">
  <ul class="content">
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
   <li>分类列表</li>
 </ul>
</div>
 
</template>

<script>

import BScroll from '@better-scroll/core'
import Pullup from '@better-scroll/pull-up'

BScroll.use(Pullup)

export default {
  name:"Category",
  data(){
    return {
      scroll:null
    }
  },
  mounted(){
    this.scroll=new BScroll('.wrapper',{
      probeType:3,
      pullUpLoad:true,
      // scrollY: true
    })

    this.scroll.on('scroll',(position)=>{
      console.log(position);
    })

    this.scroll.on('pullingUp',()=>{
      console.log('上拉加载');
      console.log('上拉加载');
      console.log('上拉加载');
      console.log('上拉加载');
      console.log('上拉加载');
      
    })
  }
}
</script>

<style>
.wrapper{
  height: 150px;
  background-color: chocolate;
  overflow: hidden;
  /* overflow-y: scroll; */
}
</style>